version: '3.9'

services:
  api:
    build:
      context: ../..
      dockerfile: code/deployment/api/Dockerfile
    image: animals10-api:latest
    container_name: animals10-api
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/models/model.pth
    volumes:
      - ../../models:/app/models:ro
    restart: unless-stopped
  app:
    build:
      context: ../..
      dockerfile: code/deployment/app/Dockerfile
    image: animals10-app:latest
    container_name: animals10-app
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped

