name: Validate on Push

on:
  push:
    branches: ["**"]

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      PROJECT_ROOT: ${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Check model exists
        run: |
          if [ ! -f models/model.pth ]; then
            echo "models/model.pth is missing. Train locally or via the pipeline before pushing." >&2
            exit 1
          fi
          echo "Model present."

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: code/deployment/api/Dockerfile
          push: false
          tags: animals10-api:validate

      - name: Build App image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: code/deployment/app/Dockerfile
          push: false
          tags: animals10-app:validate

      - name: Launch services with compose
        run: |
          cd code/deployment
          export PROJECT_ROOT="${{ github.workspace }}"
          docker compose up -d --build api app

      - name: Wait for API
        run: |
          for i in {1..30}; do
            if curl -sf http://localhost:8000/health >/dev/null; then echo OK; exit 0; fi; sleep 2; done; exit 1

      - name: Check API labels
        run: |
          curl -sf http://localhost:8000/labels | jq . | sed -e 's/.*/&/'

      - name: Stop services
        if: always()
        run: |
          cd code/deployment && docker compose down -v


